[[categories]]
title = "Posts"
  [[categories.posts]]
  title = "Humanity's Endgame"
  author = "Henry Wismayer"
  permalink = "https://www.noemamag.com/humanitys-endgame/"
  archive = "https://archive.ph/wvnUr"

  [[categories.posts]]
  title = "If all the world were a monorepo"
  author = "Julie Tibshirani"
  permalink = "https://jtibs.substack.com/p/if-all-the-world-were-a-monorepo"
  archive = "https://archive.ph/5ZOw2"

  [[categories.posts]]
  title = "Education in Brazil"
  author = "Richard Feynman"
  permalink = "https://v.cx/2010/04/feynman-brazil-education"
  archive = "https://archive.ph/BPB7Z"

  [[categories.posts]]
  title = "Why I am not a professor"
  author = "Mark Tarver"
  permalink = "https://marktarver.com/professor.html"
  archive = "https://archive.ph/g42Dn"

[[categories]]
title = "Long-form writing"
  [[categories.posts]]
  title = "How To Ask Questions The Smart Way"
  author = "Eric S. Raymond, Rick Moen"
  permalink = "http://catb.org/~esr/faqs/smart-questions.html"
  archive = "https://archive.ph/4Nsm2"

[[categories]]
title = "Series of posts"
  [[categories.posts]]
  title = "The computer of the next 200 years"
  author = "jyn, jade, ..."
  permalink = "https://jyn.dev/computer-of-the-future"
  archive = "https://archive.ph/yHkmU"

[[categories]]
title = "Video"
note = 'If any of these videos are inaccessible to you, reach out to me and I can provide you with a copy of them.  See [my views on YouTube](/writings/on-youtube).'
  [[categories.posts]]
  title = "Microsoft broke my voice"
  author = "a_lilian"
  permalink = "https://www.youtube.com/watch?v=LKcT-aQuIFs"
  suffix = "YouTube"

  [[categories.posts]]
  title = "Burn After Watching"
  author = "a_lilian"
  permalink = "https://www.youtube.com/watch?v=-IargH0hL-s"
  suffix = "YouTube"

  [[categories.posts]]
  title = "Lost Ephemera - The traces we left behind"
  author = "a_lilian"
  permalink = "https://www.youtube.com/watch?v=xbg-Jjfw2Dg"
  suffix = "YouTube"
